# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Example' do
  use_frameworks!
  pod 'ProcessOut', :path => '../'
  pod 'ProcessOutCheckout', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
