use_frameworks!
platform :ios, '10.0'
target 'ProcessOut_Example' do
  pod 'ProcessOut', :path => '../'
  pod 'Adyen3DS2', '2.1.0-rc.1'

  target 'ProcessOut_Tests' do
    inherit! :search_paths    
  end
end
