# Project Name
name: Example

# Options
options:
  deploymentTarget:
    iOS: 17.0

# Project Settings
settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
  LOCALIZATION_PREFERS_STRING_CATALOGS: true
  SWIFT_EMIT_LOC_STRINGS: true
  SWIFT_VERSION: 6.0

# SPM Packages
packages:
  ProcessOutUI:
    path: ../
  ProcessOutCheckout3DS:
    path: ../
  ProcessOutNetcetera3DS:
    path: ../

targets:
  Example:
    type: application
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
    sources: Example
    platform: iOS
    settings:
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.processout-example
      CODE_SIGN_ENTITLEMENTS: Example/Example.entitlements
    dependencies:
      - package: ProcessOutUI
      - package: ProcessOutCheckout3DS
      - package: ProcessOutNetcetera3DS

schemes:
  Example:
    build:
      targets:
        Example: all
