# Project Name
name: Example

# Options
options:
  deploymentTarget:
    iOS: 14.0

# Project Settings
settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1

# SPM Packages
packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.6.0
  ProcessOut:
    path: ../

targets:
  Example:
    type: application
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
      - path: Scripts/SwiftGen/SwiftGen.sh
        name: SwiftGen
        inputFileLists:
          - $(PROJECT_DIR)/Scripts/SwiftGen/Input.xcfilelist
        outputFileLists:
          - $(PROJECT_DIR)/Scripts/SwiftGen/Output.xcfilelist
    sources:
      - path: Example
      - path: Example/Sources/Generated/Assets+Generated.swift
        optional: true
      - path: Example/Sources/Generated/Constants+Generated.swift
        optional: true
      - path: Example/Sources/Generated/Strings+Generated.swift
        optional: true
    platform: iOS
    settings:
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.example
    dependencies:
      - package: SnapKit
      - package: ProcessOut
  ExampleUiTests:
    type: bundle.ui-testing
    sources: ExampleUiTests
    platform: iOS
    settings:
      GENERATE_INFOPLIST_FILE: 1
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.example-ui-tests
    dependencies:
      - target: Example

schemes:
  Example:
    build:
      targets:
        Example: all
        ExampleUiTests: [test]
    test:
      gatherCoverageData: true
      targets: [ExampleUiTests]
