# Project Name
name: Example

# Options
options:
  deploymentTarget:
    iOS: 17.0

# Project Settings
settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
  LOCALIZATION_PREFERS_STRING_CATALOGS: true
  SWIFT_EMIT_LOC_STRINGS: true

# SPM Packages
packages:
  ProcessOutUI:
    path: ../
  # ProcessOutCheckout3DS:
  #   path: ../

targets:
  Example:
    type: application
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
    sources: Example
    platform: iOS
    settings:
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.processout-example
    dependencies:
      - package: ProcessOutUI
      # - package: ProcessOutCheckout3DS
  ExampleUiTests:
    type: bundle.ui-testing
    sources: ExampleUiTests
    platform: iOS
    settings:
      GENERATE_INFOPLIST_FILE: 1
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.processout-example-ui-tests
    dependencies:
      - target: Example

schemes:
  Example:
    build:
      targets:
        Example: all
        ExampleUiTests: [test]
    test:
      gatherCoverageData: true
      targets: [ExampleUiTests]
