name: ProcessOut
settings:
  GENERATE_INFOPLIST_FILE: true
  CODE_SIGN_IDENTITY: ""
  GCC_TREAT_WARNINGS_AS_ERRORS: true
  SWIFT_TREAT_WARNINGS_AS_ERRORS: true
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
  SUPPORTS_MACCATALYST: false
options:
  transitivelyLinkDependencies: true
packages:
  Checkout3DSPackages:
    url: https://github.com/checkout/checkout-3ds-sdk-ios
    version: 3.2.2
targets:
  ProcessOutCoreUI:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.core-ui
      TARGET_ROOT: $(PROJECT_DIR)/Sources/ProcessOutCoreUI
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
    sources:
      - path: Sources/ProcessOutCoreUI
    dependencies:
      - framework: Vendor/cmark.xcframework
  ProcessOutUI:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.ui
      TARGET_ROOT: $(PROJECT_DIR)/Sources/ProcessOutUI
      LOCALIZED_STRING_MACRO_NAMES: "$(inherited) StringResource"
      LOCALIZATION_PREFERS_STRING_CATALOGS: true
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
    sources:
      - path: Sources/ProcessOutUI
    dependencies:
      - target: ProcessOut
      - target: ProcessOutCoreUI
  ProcessOut:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.processout-ios
      MARKETING_VERSION: ${CURRENT_VERSION}
      CURRENT_PROJECT_VERSION: 1
      SKIP_INSTALL: NO
      BUILD_LIBRARY_FOR_DISTRIBUTION: YES
      OTHER_SWIFT_FLAGS: "-Xfrontend -module-interface-preserve-types-as-written"
      TARGET_ROOT: $(PROJECT_DIR)/Sources/ProcessOut
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
      - path: Scripts/SwiftGen.sh
        name: SwiftGen
        outputFiles:
          - $(TARGET_ROOT)/Sources/Generated/Files+Generated.swift
          - $(TARGET_ROOT)/Sources/Generated/Strings+Generated.swift
        basedOnDependencyAnalysis: false
      - path: Scripts/Sourcery.sh
        name: Sourcery
        basedOnDependencyAnalysis: false
    sources:
      - path: Sources/ProcessOut
        excludes:
          - swiftgen.yml
    dependencies:
      - framework: Vendor/cmark.xcframework
  ProcessOutTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      TARGET_ROOT: $(PROJECT_DIR)/Tests/ProcessOutTests
    preBuildScripts:
      - path: Scripts/SwiftGen.sh
        name: SwiftGen
        outputFiles:
          - $(TARGET_ROOT)/Sources/Generated/Constants+Generated.swift
        basedOnDependencyAnalysis: false
    dependencies:
      - target: ProcessOut
    sources:
      - path: Tests/ProcessOutTests
      - path: Tests/ProcessOutTests/Sources/Generated/Constants+Generated.swift
        optional: true
  ProcessOutUITests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "14.0"
    settings:
      TARGET_ROOT: $(PROJECT_DIR)/Tests/ProcessOutUITests
    preBuildScripts:
      - path: Scripts/SwiftGen.sh
        name: SwiftGen
        outputFiles:
          - $(TARGET_ROOT)/Sources/Generated/Constants+Generated.swift
        basedOnDependencyAnalysis: false
    dependencies:
      - target: ProcessOutUI
    sources:
      - path: Tests/ProcessOutUITests
      - path: Tests/ProcessOutUITests/Sources/Generated/Constants+Generated.swift
        optional: true
  ProcessOutCheckout3DS:
    type: framework
    platform: iOS
    deploymentTarget: "13.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.checkout-3ds-ios
      SKIP_INSTALL: NO
      BUILD_LIBRARY_FOR_DISTRIBUTION: YES
      EXCLUDED_ARCHS: x86_64 # Checkout3DS doesn't support x86_64 so are we
      TARGET_ROOT: $(PROJECT_DIR)/Sources/ProcessOutCheckout3DS
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
    dependencies:
      - package: Checkout3DSPackages
      - target: ProcessOut
    sources: Sources/ProcessOutCheckout3DS
  ProcessOutCheckout3DSTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      TARGET_ROOT: $(PROJECT_DIR)/Tests/ProcessOutCheckout3DSTests
    dependencies:
      - target: ProcessOutCheckout3DS
    sources:
      - path: Tests/ProcessOutCheckout3DSTests
schemes:
  ProcessOut:
    build:
      targets:
        ProcessOut: all
        ProcessOutTests: [test]
    test:
      gatherCoverageData: true
      targets: [ProcessOutTests]
  ProcessOutCheckout3DS:
    build:
      targets:
        ProcessOutCheckout3DS: all
    test:
      gatherCoverageData: true
      targets: [ProcessOutCheckout3DSTests]
  ProcessOutCoreUI:
    build:
      targets:
        ProcessOutCoreUI: all
  ProcessOutUI:
    build:
      targets:
        ProcessOutUI: all
        ProcessOutUITests: [test]
    test:
      gatherCoverageData: true
      targets: [ProcessOutUITests]
