name: ProcessOut
settings:
  GENERATE_INFOPLIST_FILE: true
  CODE_SIGN_IDENTITY: ""
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
  SUPPORTS_MACCATALYST: false
  LOCALIZED_STRING_MACRO_NAMES: "$(inherited) POStringResource"
  LOCALIZATION_PREFERS_STRING_CATALOGS: true
  ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: false
  BUILD_LIBRARY_FOR_DISTRIBUTION: true
  OTHER_SWIFT_FLAGS: "$(inherited) -package-name ProcessOut"
options:
  transitivelyLinkDependencies: true
packages:
  Checkout3DSPackages:
    url: https://github.com/checkout/checkout-3ds-sdk-ios
    version: 3.2.5
  ThreeDS_SDK:
    url: https://github.com/ios-3ds-sdk/SPM.git
    version: 2.5.30
targets:
  ProcessOutCoreUI:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.core-ui
      TARGET_ROOT: $(PROJECT_DIR)/Sources/ProcessOutCoreUI
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
    sources:
      - path: Sources/ProcessOutCoreUI
    dependencies:
      - target: ProcessOut
  ProcessOutUI:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.ui
      OTHER_SWIFT_FLAGS: "$(inherited) -Xfrontend -module-interface-preserve-types-as-written -enable-upcoming-feature IsolatedDefaultValues"
      TARGET_ROOT: $(PROJECT_DIR)/Sources/ProcessOutUI
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
    sources:
      - path: Sources/ProcessOutUI
    dependencies:
      - target: ProcessOut
      - target: ProcessOutCoreUI
  ProcessOut:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.processout-ios
      MARKETING_VERSION: ${CURRENT_VERSION}
      CURRENT_PROJECT_VERSION: 1
      OTHER_SWIFT_FLAGS: "$(inherited) -Xfrontend -module-interface-preserve-types-as-written"
      TARGET_ROOT: $(PROJECT_DIR)/Sources/ProcessOut
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
      - path: Scripts/Sourcery.sh
        name: Sourcery
        basedOnDependencyAnalysis: false
    sources:
      - path: Sources/ProcessOut
    dependencies:
      - target: ProcessOutCore
      - framework: Vendor/cmark_gfm.xcframework
  ProcessOutCore:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.processout-core-ios
      MARKETING_VERSION: ${CURRENT_VERSION}
      CURRENT_PROJECT_VERSION: 1
      OTHER_SWIFT_FLAGS: "$(inherited) -Xfrontend -module-interface-preserve-types-as-written"
      TARGET_ROOT: $(PROJECT_DIR)/Sources/ProcessOutCore
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
    sources:
      - path: Sources/ProcessOutCore
  ProcessOutCoreTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      TARGET_ROOT: $(PROJECT_DIR)/Tests/ProcessOutCoreTests
    dependencies:
      - target: ProcessOutCore
    sources: Tests/ProcessOutCoreTests
  ProcessOutTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      TARGET_ROOT: $(PROJECT_DIR)/Tests/ProcessOutTests
    dependencies:
      - target: ProcessOut
    sources: Tests/ProcessOutTests
  ProcessOutUITests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      TARGET_ROOT: $(PROJECT_DIR)/Tests/ProcessOutUITests
    dependencies:
      - target: ProcessOutUI
    sources: Tests/ProcessOutUITests
  ProcessOutCheckout3DS:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.checkout-3ds-ios
      EXCLUDED_ARCHS: x86_64 # Checkout3DS doesn't support x86_64 so are we
      TARGET_ROOT: $(PROJECT_DIR)/Sources/ProcessOutCheckout3DS
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
    dependencies:
      - package: Checkout3DSPackages
      - target: ProcessOutCore
    sources: Sources/ProcessOutCheckout3DS
  ProcessOutNetcetera3DS:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.netcetera-3ds-ios
      TARGET_ROOT: $(PROJECT_DIR)/Sources/ProcessOutNetcetera3DS
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
    dependencies:
      - package: ThreeDS_SDK
      - target: ProcessOutCore
      - framework: Vendor/NetceteraShim.xcframework
    sources: Sources/ProcessOutNetcetera3DS
  ProcessOutCheckout3DSTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      TARGET_ROOT: $(PROJECT_DIR)/Tests/ProcessOutCheckout3DSTests
    dependencies:
      - target: ProcessOutCheckout3DS
    sources: Tests/ProcessOutCheckout3DSTests
  ProcessOutNetcetera3DSTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      TARGET_ROOT: $(PROJECT_DIR)/Tests/ProcessOutNetcetera3DSTests
    dependencies:
      - target: ProcessOutNetcetera3DS
    sources: Tests/ProcessOutNetcetera3DSTests
schemes:
  ProcessOutCore:
    build:
      targets:
        ProcessOutCore: all
        ProcessOutCoreTests: [test]
    test:
      gatherCoverageData: true
      targets: [ProcessOutCoreTests]
  ProcessOut:
    build:
      targets:
        ProcessOut: all
        ProcessOutTests: [test]
    test:
      gatherCoverageData: true
      targets: [ProcessOutTests]
  ProcessOutCheckout3DS:
    build:
      targets:
        ProcessOutCheckout3DS: all
    test:
      gatherCoverageData: true
      targets: [ProcessOutCheckout3DSTests]
  ProcessOutNetcetera3DS:
    build:
      targets:
        ProcessOutNetcetera3DS: all
    test:
      gatherCoverageData: true
      targets: [ProcessOutNetcetera3DSTests]
  ProcessOutCoreUI:
    build:
      targets:
        ProcessOutCoreUI: all
  ProcessOutUI:
    build:
      targets:
        ProcessOutUI: all
        ProcessOutUITests: [test]
    test:
      gatherCoverageData: true
      targets: [ProcessOutUITests]
