name: ProcessOut
settings:
  GENERATE_INFOPLIST_FILE: true
  CODE_SIGN_IDENTITY: ""
  GCC_TREAT_WARNINGS_AS_ERRORS: true
  SWIFT_TREAT_WARNINGS_AS_ERRORS: true
packages:
  CheckoutEventLoggerKit:
    url: https://github.com/checkout/checkout-event-logger-ios-framework
    from: 1.2.1
  JOSESwift:
    url: https://github.com/airsidemobile/JOSESwift
    from: 2.2.1
targets:
  ProcessOut:
    type: framework
    platform: iOS
    deploymentTarget: "12.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.processout-ios
      CURRENT_PROJECT_VERSION: ${CURRENT_VERSION}
      SKIP_INSTALL: NO
      BUILD_LIBRARY_FOR_DISTRIBUTION: YES
      OTHER_SWIFT_FLAGS: "-Xfrontend -module-interface-preserve-types-as-written"
      TARGET_ROOT: $(PROJECT_DIR)/Sources/ProcessOut
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
      - path: Scripts/SwiftGen.sh
        name: SwiftGen
        basedOnDependencyAnalysis: false
      - path: Scripts/Sourcery.sh
        name: Sourcery
        basedOnDependencyAnalysis: false
    sources:
      - path: Sources/ProcessOut
        excludes:
          - swiftgen.yml
    dependencies:
      - framework: Vendor/cmark.xcframework
  ProcessOutTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      TARGET_ROOT: $(PROJECT_DIR)/Tests/ProcessOutTests
    preBuildScripts:
      - path: Scripts/SwiftGen.sh
        name: SwiftGen
        outputFiles:
          - $(TARGET_ROOT)/Sources/Generated/Constants+Generated.swift
        basedOnDependencyAnalysis: false
    dependencies:
      - target: ProcessOut
    sources:
      - path: Tests/ProcessOutTests
      - path: Tests/ProcessOutTests/Sources/Generated/Constants+Generated.swift
        optional: true
  ProcessOutCheckout3DS:
    type: framework
    platform: iOS
    deploymentTarget: "12.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.checkout-3ds-ios
      SKIP_INSTALL: NO
      BUILD_LIBRARY_FOR_DISTRIBUTION: YES
      TARGET_ROOT: $(PROJECT_DIR)/Sources/ProcessOutCheckout3DS
    preBuildScripts:
      - path: Scripts/Lint.sh
        name: Swiftlint
        basedOnDependencyAnalysis: false
    dependencies:
      - package: CheckoutEventLoggerKit
      - package: JOSESwift
      - target: ProcessOut
    sources: Sources/ProcessOutCheckout3DS
schemes:
  ProcessOut:
    build:
      targets:
        ProcessOut: all
        ProcessOutTests: [test]
    test:
      gatherCoverageData: true
      targets: [ProcessOutTests]
  ProcessOutCheckout3DS:
    build:
      targets:
        ProcessOutCheckout3DS: all
