name: cmark_gfm
settings:
  GENERATE_INFOPLIST_FILE: YES
  CODE_SIGNING_ALLOWED: NO
targets:
  cmark_gfm:
    type: framework
    platform: iOS
    deploymentTarget: "12.0"
    settings:
      SKIP_INSTALL: NO
      BUILD_LIBRARY_FOR_DISTRIBUTION: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.swiftlang.cmark
      MARKETING_VERSION: ${CURRENT_REVISION}
      CURRENT_PROJECT_VERSION: 1
      MODULEMAP_FILE: src/include/module.modulemap
    sources:
      - path: src
        excludes:
          - "*.inc"
          - "*.re"
          - "*.in"
          - "*.txt"
schemes:
  cmark_gfm:
    build:
      targets:
        cmark_gfm: all
