name: cmark
settings:
  GENERATE_INFOPLIST_FILE: YES
  CODE_SIGNING_ALLOWED: NO
targets:
  cmark:
    type: framework
    platform: iOS
    deploymentTarget: "12.0"
    settings:
      SKIP_INSTALL: NO
      BUILD_LIBRARY_FOR_DISTRIBUTION: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.processout.cmark-ios
      MARKETING_VERSION: ${CURRENT_VERSION}
      CURRENT_PROJECT_VERSION: 1
      MODULEMAP_FILE: src/module.modulemap
    sources:
      - path: src
        excludes:
          - "main.c"
          - "man.c"
          - "*.inc"
          - "*.re"
          - "*.in"
          - "*.txt"
schemes:
  cmark:
    build:
      targets:
        cmark: all
