# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  lane :tests do
    run_tests(project: "ProcessOut.xcodeproj", scheme: "ProcessOut", device: "iPhone 14 Pro (16.2)", clean: true)
  end

  lane :example_tests do
    run_tests(project: "Example/Example.xcodeproj", scheme: "Example", device: "iPhone 14 Pro (16.2)", clean: true)
  end
end
