name: Create Release Candidate
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'minor'
        type: choice
        options:
          - minor
          - patch
          - major

permissions:
  contents: read

jobs:
  update-version:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Update Version
        run: |
          source Scripts/UpdateVersion.sh --${{ inputs.release_type }}
          echo "UPDATED_VERSION=$(cat Version.resolved)" >> $GITHUB_ENV
      - name: Mint App token
        id: app-token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 #v2
        with:
          app-id: ${{ vars.CKO_PUBLIC_WRITE_APP_ID }}
          private-key: ${{ secrets.CKO_PUBLIC_WRITE_APP_KEY }}
          owner: processout
          repositories: processout-ios
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          add-paths: |
            *.podspec
            Version.resolved
            Sources/**/*.swift
          commit-message: Update version
          branch: release/${{ env.UPDATED_VERSION }}
          delete-branch: true
          title: 'feat(release): ${{ env.UPDATED_VERSION }}'
          assignees: ${{ github.actor }}
