name: Create Release Candidate
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'minor'
        type: choice
        options:
          - minor
          - patch
          - major
jobs:
  update-version:
    runs-on: macos-12
    outputs:
      pull-request-head-sha: ${{ steps.cpr.outputs.pull-request-head-sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Update Version
        run: |
          source Scripts/UpdateVersion.sh --${{ inputs.release_type }}
          echo "UPDATED_VERSION=$(cat Version.resolved)" >> $GITHUB_ENV
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: |
            ProcessOut.podspec
            Version.resolved
            Sources/**/*.swift
          commit-message: Update version
          branch: release/${{ env.UPDATED_VERSION }}
          delete-branch: true
          title: 'feat(release): ${{ env.UPDATED_VERSION }}'
          assignees: ${{ github.actor }}
  run-tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      reference: ${{ needs.update-version.outputs.pull-request-head-sha }}
    needs: update-version
