name: 'Push Podspecs'
on:
  push:
jobs:
  run-tests:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Push Podspecs
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push ProcessOutCheckout3DS.podspec --allow-warnings
