name: Release Documentation
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  release-documentation:
    name: Release Documentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap Project
        uses: ./.github/actions/bootstrap-project
      - name: Build Documentation
        run: source Scripts/CreateDocumentation.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'Docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
