name: Upload to TestFlighs
on:
  # todo(andrii-vysotskyi): remove PR trigger after testing
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  export:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode Version
        uses: ./.github/actions/select-xcode
      - name: Bootstrap Project
        working-directory: ./Example
        run: ./Scripts/BootstrapProject.sh
      - name: Export
        working-directory: ./Example
        env:
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
        run: ./Scripts/Export/Export.sh
